#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_WanderingTraderAI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct AnimBP_WanderingTraderAI.AnimBP_WanderingTraderAI_C.AnimBlueprintGeneratedConstantData
// 0x0197 (0x0198 - 0x0001)
struct AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_879;                                // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_880;                                // 0x000C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_881;                                 // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_882;                                // 0x0018(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_883;                                 // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_884;                                // 0x0024(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_885;                                 // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_886;                                // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_887;                                 // 0x0038(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_888;                                // 0x003C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_889;                                 // 0x0044(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_890;                              // 0x0048(0x002C)(BlueprintVisible, NoDestructor)
	class FName                                   __NameProperty_891;                                // 0x0074(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_892;                                 // 0x007C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 __ArrayProperty_893;                               // 0x0080(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_894;                                // 0x0090(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_895;                                 // 0x0098(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_896;                                // 0x009C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_897;                               // 0x00A0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_898;                               // 0x00A4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_899;                                // 0x00A8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_900;                                // 0x00A9(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AA[0x2];                                       // 0x00AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_901;                                // 0x00AC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlendProfile*                          __BlendProfile_902;                                // 0x00B8(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_903;                                  // 0x00C0(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_904;                                // 0x00C8(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_905;                                // 0x00C9(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_906;                                // 0x00CA(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CB[0x5];                                       // 0x00CB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_907;                               // 0x00D0(0x0010)(BlueprintVisible, EditFixedSize)
	struct FAnimNodeFunctionRef                   __StructProperty_908;                              // 0x00E0(0x0020)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0100(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0180(0x0018)()
};
static_assert(alignof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData) == 0x000198, "Wrong size on AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_879) == 0x000004, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_879' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_880) == 0x00000C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_880' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_881) == 0x000014, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_881' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_882) == 0x000018, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_882' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_883) == 0x000020, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_883' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_884) == 0x000024, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_884' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_885) == 0x00002C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_885' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_886) == 0x000030, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_886' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_887) == 0x000038, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_887' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_888) == 0x00003C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_888' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_889) == 0x000044, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_889' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __StructProperty_890) == 0x000048, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__StructProperty_890' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_891) == 0x000074, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_891' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_892) == 0x00007C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_892' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __ArrayProperty_893) == 0x000080, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__ArrayProperty_893' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_894) == 0x000090, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_894' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __IntProperty_895) == 0x000098, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__IntProperty_895' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __BoolProperty_896) == 0x00009C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__BoolProperty_896' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __FloatProperty_897) == 0x0000A0, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__FloatProperty_897' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __FloatProperty_898) == 0x0000A4, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__FloatProperty_898' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __EnumProperty_899) == 0x0000A8, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__EnumProperty_899' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __ByteProperty_900) == 0x0000A9, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__ByteProperty_900' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __NameProperty_901) == 0x0000AC, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__NameProperty_901' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __BlendProfile_902) == 0x0000B8, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__BlendProfile_902' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __CurveFloat_903) == 0x0000C0, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__CurveFloat_903' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __BoolProperty_904) == 0x0000C8, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__BoolProperty_904' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __EnumProperty_905) == 0x0000C9, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__EnumProperty_905' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __EnumProperty_906) == 0x0000CA, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__EnumProperty_906' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __ArrayProperty_907) == 0x0000D0, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__ArrayProperty_907' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, __StructProperty_908) == 0x0000E0, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::__StructProperty_908' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000100, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000180, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct AnimBP_WanderingTraderAI.AnimBP_WanderingTraderAI_C.AnimBlueprintGeneratedMutableData
// 0x007F (0x0080 - 0x0001)
struct AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	bool                                          __BoolProperty;                                    // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_1;                                  // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_2;                                  // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_3;                                  // 0x0005(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_4;                                  // 0x0006(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_5;                                  // 0x0007(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_6;                                  // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_7;                                 // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_8;                                 // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_9;                                  // 0x0014(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_10;                                // 0x0018(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_11;                                 // 0x001C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_12;                                // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_13;                                 // 0x0024(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_14;                                // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_15;                                // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_16;                                 // 0x0030(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_17;                                 // 0x0031(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_18;                                 // 0x0032(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_19;                                 // 0x0033(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_20;                                 // 0x0034(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_21;                                 // 0x0035(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_22;                                 // 0x0036(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_23;                                 // 0x0037(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_24;                                 // 0x0038(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_25;                                 // 0x0039(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_26;                                 // 0x003A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_27;                                 // 0x003B(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_28;                                 // 0x003C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_29;                                // 0x0040(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_30;                                // 0x0044(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_31;                                 // 0x0048(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_32;                                // 0x004C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_33;                                // 0x0050(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_34;                                 // 0x0054(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_35;                                // 0x0058(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_36;                                // 0x005C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_37;                                 // 0x0060(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_38;                                // 0x0064(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_39;                                // 0x0068(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_40;                                // 0x006C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_41;                                // 0x0070(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_42;                                 // 0x0074(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_75[0x3];                                       // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_43;                                // 0x0078(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_44;                                 // 0x007C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData) == 0x000004, "Wrong alignment on AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData) == 0x000080, "Wrong size on AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty) == 0x000001, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000002, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_1) == 0x000003, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_1' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_2) == 0x000004, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_2' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_3) == 0x000005, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_3' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_4) == 0x000006, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_4' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_5) == 0x000007, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_5' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_6) == 0x000008, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_6' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_7) == 0x00000C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_7' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_8) == 0x000010, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_8' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_9) == 0x000014, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_9' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_10) == 0x000018, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_10' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_11) == 0x00001C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_11' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_12) == 0x000020, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_12' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_13) == 0x000024, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_13' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_14) == 0x000028, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_14' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_15) == 0x00002C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_15' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_16) == 0x000030, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_16' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_17) == 0x000031, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_17' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_18) == 0x000032, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_18' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_19) == 0x000033, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_19' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_20) == 0x000034, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_20' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_21) == 0x000035, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_21' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_22) == 0x000036, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_22' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_23) == 0x000037, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_23' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_24) == 0x000038, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_24' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_25) == 0x000039, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_25' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_26) == 0x00003A, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_26' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_27) == 0x00003B, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_27' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_28) == 0x00003C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_28' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_29) == 0x000040, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_29' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_30) == 0x000044, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_30' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_31) == 0x000048, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_31' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_32) == 0x00004C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_32' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_33) == 0x000050, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_33' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_34) == 0x000054, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_34' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_35) == 0x000058, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_35' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_36) == 0x00005C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_36' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_37) == 0x000060, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_37' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_38) == 0x000064, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_38' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_39) == 0x000068, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_39' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_40) == 0x00006C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_40' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_41) == 0x000070, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_41' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_42) == 0x000074, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_42' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __FloatProperty_43) == 0x000078, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__FloatProperty_43' has a wrong offset!");
static_assert(offsetof(AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData, __BoolProperty_44) == 0x00007C, "Member 'AnimBP_WanderingTraderAI::FAnimBlueprintGeneratedMutableData::__BoolProperty_44' has a wrong offset!");

}

