#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_50CalAmmoPickup

#include "Basic.hpp"

#include "BP_StaticMeshPickup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_50CalAmmoPickup.BP_50CalAmmoPickup_C
// 0x0000 (0x0310 - 0x0310)
class ABP_50CalAmmoPickup_C final : public ABP_StaticMeshPickup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_50CalAmmoPickup_C">();
	}
	static class ABP_50CalAmmoPickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_50CalAmmoPickup_C>();
	}
};
static_assert(alignof(ABP_50CalAmmoPickup_C) == 0x000008, "Wrong alignment on ABP_50CalAmmoPickup_C");
static_assert(sizeof(ABP_50CalAmmoPickup_C) == 0x000310, "Wrong size on ABP_50CalAmmoPickup_C");

}

