#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnterArea

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "S_NotificationDetails_structs.hpp"


namespace SDK::Params
{

// Function BP_EnterArea.BP_EnterArea_C.ExecuteUbergraph_BP_EnterArea
// 0x0290 (0x0290 - 0x0000)
struct BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0028(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x012D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12E[0x2];                                      // 0x012E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character;          // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character_1;        // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_CustomEvent_Actor_1;                        // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_164[0x4];                                      // 0x0164(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_MasterPlayerController_C*           K2Node_DynamicCast_AsBP_Master_Player_Controller;  // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AHUD_Game_C*                            K2Node_DynamicCast_AsHUD_Game;                     // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_CustomEvent_Actor;                          // 0x0190(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_MasterPlayerController_C*           K2Node_DynamicCast_AsBP_Master_Player_Controller_1; // 0x01A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A9[0x3];                                      // 0x01A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x01AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BC[0x4];                                      // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x01C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue_1;                     // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AHUD_Game_C*                            K2Node_DynamicCast_AsHUD_Game_1;                   // 0x01D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D9[0x3];                                      // 0x01D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x01DC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USD_GameInstance_C*                     CallFunc_GetGameInstance_Instance;                 // 0x01F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x01F8(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetOverlappingActors_OverlappingActors;   // 0x0208(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0218(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0224(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0225(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_226[0x2];                                      // 0x0226(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character_2;        // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_231[0x7];                                      // 0x0231(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUD_Game_C*                            CallFunc_GetGameHUD_HUD;                           // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FS_NotificationDetails                 K2Node_MakeStruct_S_NotificationDetails;           // 0x0240(0x0040)(HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0280(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea) == 0x000008, "Wrong alignment on BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea");
static_assert(sizeof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea) == 0x000290, "Wrong size on BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, EntryPoint) == 0x000000, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_bool_IsClosed_Variable) == 0x000004, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_bool_Has_Been_Initd_Variable) == 0x000005, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_bool_IsClosed_Variable_1) == 0x000006, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_bool_Has_Been_Initd_Variable_1) == 0x000007, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000008, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000010, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000018, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000020, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_bFromSweep) == 0x000024, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_SweepResult) == 0x000028, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000110, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherActor) == 0x000118, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherComp) == 0x000120, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000128, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_IsValid_ReturnValue) == 0x00012C, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_IsValid_ReturnValue_1) == 0x00012D, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsBP_Player_Character) == 0x000130, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsBP_Player_Character' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess) == 0x000138, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsBP_Player_Character_1) == 0x000140, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsBP_Player_Character_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_1) == 0x000148, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_CustomEvent_Actor_1) == 0x000150, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_CustomEvent_Actor_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetController_ReturnValue) == 0x000158, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_int_Loop_Counter_Variable) == 0x000160, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsBP_Master_Player_Controller) == 0x000168, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsBP_Master_Player_Controller' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_2) == 0x000170, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_Add_IntInt_ReturnValue) == 0x000174, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetHUD_ReturnValue) == 0x000178, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsHUD_Game) == 0x000180, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsHUD_Game' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_3) == 0x000188, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_CustomEvent_Actor) == 0x000190, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_CustomEvent_Actor' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetController_ReturnValue_1) == 0x000198, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsBP_Master_Player_Controller_1) == 0x0001A0, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsBP_Master_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_4) == 0x0001A8, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_CreateDelegate_OutputDelegate) == 0x0001AC, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0001C0, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetHUD_ReturnValue_1) == 0x0001C8, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetHUD_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsHUD_Game_1) == 0x0001D0, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsHUD_Game_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_5) == 0x0001D8, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_CreateDelegate_OutputDelegate_1) == 0x0001DC, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetGameInstance_Instance) == 0x0001F0, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetGameInstance_Instance' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x0001F8, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, Temp_int_Array_Index_Variable) == 0x000200, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetOverlappingActors_OverlappingActors) == 0x000208, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetOverlappingActors_OverlappingActors' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_Array_Get_Item) == 0x000218, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_Array_Length_ReturnValue) == 0x000220, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_IsValid_ReturnValue_2) == 0x000224, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_Less_IntInt_ReturnValue) == 0x000225, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_AsBP_Player_Character_2) == 0x000228, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_AsBP_Player_Character_2' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_DynamicCast_bSuccess_6) == 0x000230, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, CallFunc_GetGameHUD_HUD) == 0x000238, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::CallFunc_GetGameHUD_HUD' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_MakeStruct_S_NotificationDetails) == 0x000240, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_MakeStruct_S_NotificationDetails' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea, K2Node_CreateDelegate_OutputDelegate_2) == 0x000280, "Member 'BP_EnterArea_C_ExecuteUbergraph_BP_EnterArea::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");

// Function BP_EnterArea.BP_EnterArea_C.Event_ExitedArea
// 0x0008 (0x0008 - 0x0000)
struct BP_EnterArea_C_Event_ExitedArea final
{
public:
	class ABP_PlayerCharacter_C*                  Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EnterArea_C_Event_ExitedArea) == 0x000008, "Wrong alignment on BP_EnterArea_C_Event_ExitedArea");
static_assert(sizeof(BP_EnterArea_C_Event_ExitedArea) == 0x000008, "Wrong size on BP_EnterArea_C_Event_ExitedArea");
static_assert(offsetof(BP_EnterArea_C_Event_ExitedArea, Actor) == 0x000000, "Member 'BP_EnterArea_C_Event_ExitedArea::Actor' has a wrong offset!");

// Function BP_EnterArea.BP_EnterArea_C.Event_EnteredArea
// 0x0008 (0x0008 - 0x0000)
struct BP_EnterArea_C_Event_EnteredArea final
{
public:
	class ABP_PlayerCharacter_C*                  Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EnterArea_C_Event_EnteredArea) == 0x000008, "Wrong alignment on BP_EnterArea_C_Event_EnteredArea");
static_assert(sizeof(BP_EnterArea_C_Event_EnteredArea) == 0x000008, "Wrong size on BP_EnterArea_C_Event_EnteredArea");
static_assert(offsetof(BP_EnterArea_C_Event_EnteredArea, Actor) == 0x000000, "Member 'BP_EnterArea_C_Event_EnteredArea::Actor' has a wrong offset!");

// Function BP_EnterArea.BP_EnterArea_C.BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function BP_EnterArea.BP_EnterArea_C.BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_EnterArea_C_BndEvt__BP_RadiationArea_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

}

