#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FlickeringLightSparks

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_FlickeringLightSparks.BP_FlickeringLightSparks_C.BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature final
{
public:
	bool                                          bIsBeyondLastLayer;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LayerIndex;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSeen;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x000004, "Wrong alignment on BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(sizeof(BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x00000C, "Wrong size on BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(offsetof(BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsBeyondLastLayer) == 0x000000, "Member 'BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, LayerIndex) == 0x000004, "Member 'BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsSeen) == 0x000008, "Member 'BP_FlickeringLightSparks_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsSeen' has a wrong offset!");

// Function BP_FlickeringLightSparks.BP_FlickeringLightSparks_C.ExecuteUbergraph_BP_FlickeringLightSparks
// 0x0048 (0x0048 - 0x0000)
struct BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsBeyondLastLayer;     // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_ComponentBoundEvent_LayerIndex;             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSeen;                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetIntensity_NewIntensity_ImplicitCast;   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast_1;            // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks) == 0x000008, "Wrong alignment on BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks");
static_assert(sizeof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks) == 0x000048, "Wrong size on BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, EntryPoint) == 0x000000, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_RandomFloatInRange_ReturnValue) == 0x000008, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000010, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000018, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, K2Node_ComponentBoundEvent_bIsBeyondLastLayer) == 0x000020, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::K2Node_ComponentBoundEvent_bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, K2Node_ComponentBoundEvent_LayerIndex) == 0x000024, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::K2Node_ComponentBoundEvent_LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, K2Node_ComponentBoundEvent_bIsSeen) == 0x000028, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::K2Node_ComponentBoundEvent_bIsSeen' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000030, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_Delay_Duration_ImplicitCast) == 0x000038, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_SetIntensity_NewIntensity_ImplicitCast) == 0x00003C, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_SetIntensity_NewIntensity_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks, CallFunc_Delay_Duration_ImplicitCast_1) == 0x000040, "Member 'BP_FlickeringLightSparks_C_ExecuteUbergraph_BP_FlickeringLightSparks::CallFunc_Delay_Duration_ImplicitCast_1' has a wrong offset!");

// Function BP_FlickeringLightSparks.BP_FlickeringLightSparks_C.UserConstructionScript
// 0x00F0 (0x00F0 - 0x0000)
struct BP_FlickeringLightSparks_C_UserConstructionScript final
{
public:
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0000(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_SetSourceRadius_bNewValue_ImplicitCast;   // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetSourceLength_NewValue_ImplicitCast;    // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FlickeringLightSparks_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_FlickeringLightSparks_C_UserConstructionScript");
static_assert(sizeof(BP_FlickeringLightSparks_C_UserConstructionScript) == 0x0000F0, "Wrong size on BP_FlickeringLightSparks_C_UserConstructionScript");
static_assert(offsetof(BP_FlickeringLightSparks_C_UserConstructionScript, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000000, "Member 'BP_FlickeringLightSparks_C_UserConstructionScript::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_UserConstructionScript, CallFunc_SetSourceRadius_bNewValue_ImplicitCast) == 0x0000E8, "Member 'BP_FlickeringLightSparks_C_UserConstructionScript::CallFunc_SetSourceRadius_bNewValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_FlickeringLightSparks_C_UserConstructionScript, CallFunc_SetSourceLength_NewValue_ImplicitCast) == 0x0000EC, "Member 'BP_FlickeringLightSparks_C_UserConstructionScript::CallFunc_SetSourceLength_NewValue_ImplicitCast' has a wrong offset!");

}

