#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JigControllerSupport

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JigControllerSupport.BP_JigControllerSupport_C
// 0x0008 (0x00A8 - 0x00A0)
class UBP_JigControllerSupport_C final : public UActorComponent
{
public:
	bool                                          ControllerEnabled;                                 // 0x00A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void IsControllerEnabled(bool* ControllerEnabled_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_JigControllerSupport_C">();
	}
	static class UBP_JigControllerSupport_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_JigControllerSupport_C>();
	}
};
static_assert(alignof(UBP_JigControllerSupport_C) == 0x000008, "Wrong alignment on UBP_JigControllerSupport_C");
static_assert(sizeof(UBP_JigControllerSupport_C) == 0x0000A8, "Wrong size on UBP_JigControllerSupport_C");
static_assert(offsetof(UBP_JigControllerSupport_C, ControllerEnabled) == 0x0000A0, "Member 'UBP_JigControllerSupport_C::ControllerEnabled' has a wrong offset!");

}

