#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KeycardBriefcaseContainer

#include "Basic.hpp"

#include "BP_KeycardBriefcaseContainer_classes.hpp"
#include "BP_KeycardBriefcaseContainer_parameters.hpp"


namespace SDK
{

// Function BP_KeycardBriefcaseContainer.BP_KeycardBriefcaseContainer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_KeycardBriefcaseContainer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_KeycardBriefcaseContainer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_KeycardBriefcaseContainer.BP_KeycardBriefcaseContainer_C.ExecuteUbergraph_BP_KeycardBriefcaseContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_KeycardBriefcaseContainer_C::ExecuteUbergraph_BP_KeycardBriefcaseContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_KeycardBriefcaseContainer_C", "ExecuteUbergraph_BP_KeycardBriefcaseContainer");

	Params::BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_KeycardBriefcaseContainer.BP_KeycardBriefcaseContainer_C.Event2
// (BlueprintCallable, BlueprintEvent)

void ABP_KeycardBriefcaseContainer_C::Event2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_KeycardBriefcaseContainer_C", "Event2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_KeycardBriefcaseContainer.BP_KeycardBriefcaseContainer_C.Event1
// (BlueprintCallable, BlueprintEvent)

void ABP_KeycardBriefcaseContainer_C::Event1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_KeycardBriefcaseContainer_C", "Event1");

	UObject::ProcessEvent(Func, nullptr);
}

}

