#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KeycardBriefcaseContainer

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_KeycardBriefcaseContainer.BP_KeycardBriefcaseContainer_C.ExecuteUbergraph_BP_KeycardBriefcaseContainer
// 0x0024 (0x0024 - 0x0000)
struct BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer) == 0x000004, "Wrong alignment on BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer");
static_assert(sizeof(BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer) == 0x000024, "Wrong size on BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer");
static_assert(offsetof(BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer, EntryPoint) == 0x000000, "Member 'BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'BP_KeycardBriefcaseContainer_C_ExecuteUbergraph_BP_KeycardBriefcaseContainer::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");

}

