#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LechieScopePickup

#include "Basic.hpp"

#include "BP_StaticMeshPickup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LechieScopePickup.BP_LechieScopePickup_C
// 0x0000 (0x0310 - 0x0310)
class ABP_LechieScopePickup_C final : public ABP_StaticMeshPickup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LechieScopePickup_C">();
	}
	static class ABP_LechieScopePickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LechieScopePickup_C>();
	}
};
static_assert(alignof(ABP_LechieScopePickup_C) == 0x000008, "Wrong alignment on ABP_LechieScopePickup_C");
static_assert(sizeof(ABP_LechieScopePickup_C) == 0x000310, "Wrong size on ABP_LechieScopePickup_C");

}

