#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ladder

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Ladder.BP_Ladder_C.BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature final
{
public:
	bool                                          bIsBeyondLastLayer;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LayerIndex;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSeen;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x000004, "Wrong alignment on BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(sizeof(BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x00000C, "Wrong size on BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsBeyondLastLayer) == 0x000000, "Member 'BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, LayerIndex) == 0x000004, "Member 'BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsSeen) == 0x000008, "Member 'BP_Ladder_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsSeen' has a wrong offset!");

// Function BP_Ladder.BP_Ladder_C.BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_Ladder.BP_Ladder_C.BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_Ladder_C_BndEvt__BP_Ladder_LadderCollision_K2Node_ComponentBoundEvent_7_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function BP_Ladder.BP_Ladder_C.BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0108 (0x0108 - 0x0000)
struct BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000108, "Wrong size on BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_Ladder_C_BndEvt__BP_LadderNew_LadderTopCollision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_Ladder.BP_Ladder_C.ExecuteUbergraph_BP_Ladder
// 0x05D0 (0x05D0 - 0x0000)
struct BP_Ladder_C_ExecuteUbergraph_BP_Ladder final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsBeyondLastLayer;     // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_ComponentBoundEvent_LayerIndex;             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSeen;                // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_2;  // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_2;           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_2;            // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_2;       // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep_1;           // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult_1;          // 0x0030(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character;          // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character_1;        // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0158(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0188(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x01A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x01BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BD[0x3];                                      // 0x01BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x01C0(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_BreakVector_X_1;                          // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x02B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_PlayerCharacter_C*                  K2Node_DynamicCast_AsBP_Player_Character_2;        // 0x02C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x02D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x02E8(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x03D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D1[0x7];                                      // 0x03D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x03D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_2;                          // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_2;                          // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_2;                          // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0410(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0428(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        CallFunc_BreakVector_X_3;                          // 0x0440(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_3;                          // 0x0448(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_3;                          // 0x0450(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0458(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x045C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0460(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_464[0x4];                                      // 0x0464(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0468(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0480(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult_1;     // 0x0498(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue_1;        // 0x0580(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x0581(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_582[0x6];                                      // 0x0582(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue_1;    // 0x0588(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll_1;                      // 0x05A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch_1;                     // 0x05A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw_1;                       // 0x05A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5AC[0x4];                                      // 0x05AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x05B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue_1;        // 0x05C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x05C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x05CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder) == 0x000008, "Wrong alignment on BP_Ladder_C_ExecuteUbergraph_BP_Ladder");
static_assert(sizeof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder) == 0x0005D0, "Wrong size on BP_Ladder_C_ExecuteUbergraph_BP_Ladder");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, EntryPoint) == 0x000000, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_bIsBeyondLastLayer) == 0x000004, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_LayerIndex) == 0x000008, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_LayerIndex' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_bIsSeen) == 0x00000C, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_bIsSeen' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OverlappedComponent_2) == 0x000010, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OverlappedComponent_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherActor_2) == 0x000018, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherActor_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherComp_2) == 0x000020, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherComp_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherBodyIndex_2) == 0x000028, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherBodyIndex_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_bFromSweep_1) == 0x00002C, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_bFromSweep_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_SweepResult_1) == 0x000030, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_SweepResult_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000118, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000120, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000128, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000130, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_AsBP_Player_Character) == 0x000138, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_AsBP_Player_Character' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_bSuccess) == 0x000140, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_AsBP_Player_Character_1) == 0x000148, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_AsBP_Player_Character_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_bSuccess_1) == 0x000150, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000158, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_X) == 0x000170, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Y) == 0x000178, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Z) == 0x000180, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000188, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x0001A0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherActor) == 0x0001A8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherComp) == 0x0001B0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x0001B8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_bFromSweep) == 0x0001BC, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_ComponentBoundEvent_SweepResult) == 0x0001C0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_X_1) == 0x0002A8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Y_1) == 0x0002B0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Z_1) == 0x0002B8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_AsBP_Player_Character_2) == 0x0002C0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_AsBP_Player_Character_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, K2Node_DynamicCast_bSuccess_2) == 0x0002C8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_MakeVector_ReturnValue) == 0x0002D0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x0002E8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorLocation_ReturnValue) == 0x0003D0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0003D8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_X_2) == 0x0003F0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_X_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Y_2) == 0x0003F8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Y_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Z_2) == 0x000400, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Z_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000408, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000410, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000428, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_X_3) == 0x000440, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_X_3' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Y_3) == 0x000448, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Y_3' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakVector_Z_3) == 0x000450, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakVector_Z_3' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Roll) == 0x000458, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Pitch) == 0x00045C, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Yaw) == 0x000460, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_MakeVector_ReturnValue_1) == 0x000468, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_MakeRotator_ReturnValue) == 0x000480, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorLocation_SweepHitResult_1) == 0x000498, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorLocation_ReturnValue_1) == 0x000580, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorRotation_ReturnValue) == 0x000581, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_GetComponentRotation_ReturnValue_1) == 0x000588, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_GetComponentRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Roll_1) == 0x0005A0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Roll_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Pitch_1) == 0x0005A4, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Pitch_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_BreakRotator_Yaw_1) == 0x0005A8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_BreakRotator_Yaw_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_MakeRotator_ReturnValue_1) == 0x0005B0, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_K2_SetActorRotation_ReturnValue_1) == 0x0005C8, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_K2_SetActorRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_IsValid_ReturnValue) == 0x0005C9, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_ExecuteUbergraph_BP_Ladder, CallFunc_IsValid_ReturnValue_1) == 0x0005CA, "Member 'BP_Ladder_C_ExecuteUbergraph_BP_Ladder::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function BP_Ladder.BP_Ladder_C.UserConstructionScript
// 0x0430 (0x0430 - 0x0000)
struct BP_Ladder_C_UserConstructionScript final
{
public:
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x0038(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_BreakVector_X;                            // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_2;           // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0148(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0160(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_2;           // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0280(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x0298(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02B0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult_1;  // 0x0310(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UStaticMeshComponent*                   CallFunc_AddComponent_ReturnValue;                 // 0x03F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_3;                 // 0x0400(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue_1;                      // 0x0418(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FMod_Remainder;                           // 0x0420(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FMod_ReturnValue;                         // 0x0428(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x042C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Ladder_C_UserConstructionScript) == 0x000010, "Wrong alignment on BP_Ladder_C_UserConstructionScript");
static_assert(sizeof(BP_Ladder_C_UserConstructionScript) == 0x000430, "Wrong size on BP_Ladder_C_UserConstructionScript");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000000, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, Temp_int_Variable) == 0x000008, "Member 'BP_Ladder_C_UserConstructionScript::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x000010, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_IsValid_ReturnValue) == 0x00001C, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x000020, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x000038, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_BreakVector_X) == 0x000120, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_BreakVector_Y) == 0x000128, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_BreakVector_Z) == 0x000130, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Conv_IntToDouble_ReturnValue_2) == 0x000138, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Conv_IntToDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000140, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_MakeVector_ReturnValue) == 0x000148, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000160, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_VSize_ReturnValue) == 0x000248, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000250, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000258, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000260, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000268, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x000270, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_Add_DoubleDouble_ReturnValue_2) == 0x000278, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_Add_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_MakeVector_ReturnValue_1) == 0x000280, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_MakeVector_ReturnValue_2) == 0x000298, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_MakeTransform_ReturnValue) == 0x0002B0, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_K2_SetRelativeLocation_SweepHitResult_1) == 0x000310, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_K2_SetRelativeLocation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_AddComponent_ReturnValue) == 0x0003F8, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_AddComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_MakeVector_ReturnValue_3) == 0x000400, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_MakeVector_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_VSize_ReturnValue_1) == 0x000418, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_VSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_FMod_Remainder) == 0x000420, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_FMod_Remainder' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_FMod_ReturnValue) == 0x000428, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_FMod_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Ladder_C_UserConstructionScript, CallFunc_LessEqual_IntInt_ReturnValue) == 0x00042C, "Member 'BP_Ladder_C_UserConstructionScript::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");

}

