#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MP5Pickup

#include "Basic.hpp"

#include "BP_FirearmPickup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MP5Pickup.BP_MP5Pickup_C
// 0x0000 (0x0410 - 0x0410)
class ABP_MP5Pickup_C final : public ABP_FirearmPickup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MP5Pickup_C">();
	}
	static class ABP_MP5Pickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MP5Pickup_C>();
	}
};
static_assert(alignof(ABP_MP5Pickup_C) == 0x000008, "Wrong alignment on ABP_MP5Pickup_C");
static_assert(sizeof(ABP_MP5Pickup_C) == 0x000410, "Wrong size on ABP_MP5Pickup_C");

}

