#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MASTER_ToolRequiredContainer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "S_InvWeight_structs.hpp"
#include "Enum_ContainerLootTables_structs.hpp"
#include "S_ReplicatedContainerInfo_structs.hpp"
#include "BP_MasterObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MASTER_ToolRequiredContainer.BP_MASTER_ToolRequiredContainer_C
// 0x0170 (0x0410 - 0x02A0)
class ABP_MASTER_ToolRequiredContainer_C : public ABP_MasterObject_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAIOSubjectComponent*                   AIOSubject;                                        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_JigMultiplayer_C*                   BP_JigMultiplayer;                                 // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                InteractingActorLoc;                               // 0x02C0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CurrentActor;                                      // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Outline_;                                          // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHeld;                                            // 0x02E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_ContainerLootTables                      LootTable;                                         // 0x02E2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E3[0x5];                                      // 0x02E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DurationToHold;                                    // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ChanceToMakeNoise;                                 // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DefaultChanceToProduceNoise;                       // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   ContainerName;                                     // 0x0300(0x0018)(Edit, BlueprintVisible)
	class UJigsawItem_DataAsset_C*                ToolNeeded;                                        // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Opened;                                            // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OpenedObject;                                      // 0x0328(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ContainerLooted;                                   // 0x0338(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ToolNeeded_;                                       // 0x0339(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33A[0x6];                                      // 0x033A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           OutlineTimer;                                      // 0x0340(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          PlayerClose_;                                      // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_349[0x7];                                      // 0x0349(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           HoldToInteractTimer;                               // 0x0350(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SearchSoundComp;                                   // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        RefillTimer;                                       // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_368[0x8];                                      // 0x0368(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             MagnifierTransform;                                // 0x0370(0x0060)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       W_MagnifierUI;                                     // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FS_ReplicatedContainerInfo>     MainJigContainers;                                 // 0x03D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame, ContainsInstancedReference)
	TArray<struct FGuid>                          MainUIDs;                                          // 0x03E8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame)
	TArray<struct FS_InvWeight>                   Weights;                                           // 0x03F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame)

public:
	void UserConstructionScript();
	void TraceToPlayer(bool* HitObject_);
	void TraceForActor(bool* Ouput);
	void SetPickupCount(int32 NewCount, bool* Result);
	void SetInteractOption(const struct FGameplayTag& Option);
	void SetInteractDistance(class AActor* Target);
	void SetInspected(bool Inspected);
	void SearchSound(bool Spawn_);
	void ReceiveBeginPlay();
	void PickupBuildFromGround();
	void PauseInteract();
	void OpenContainer();
	void OnStopExecuteInteract(class AActor* InteractingActor);
	void OnServerExecuteInteract(const struct FGameplayTag& Option, class AActor* ByActor, const struct FS_JigPayload& Payload);
	void OnRequestServerInteract(class AActor* Actor, const struct FGameplayTag& Option, const struct FS_JigPayload& Payload, bool* Result);
	void OnExecuteInteractEnded();
	void OnExecuteInteractDialogue(class AActor* InteractingActor);
	void OnExecuteInteract(class AActor* InteractingActor, const struct FGameplayTag& Option);
	void OnEndInteract();
	void OnBeginInteract(class AActor* InteractingActor, const TMap<struct FGameplayTag, class FText>& Options);
	void NoiseEvent();
	void JigSetCanInteract(bool CanInteract, bool EnablePhysics, bool* Result);
	void JigMP_OnUpdateChamberUID(const struct FGuid& NewUID, bool* Result);
	void JigMP_OnTwoContainersSwap(class FName FromContainer, class FName ToContainer, bool* Result);
	void JigMP_OnRequestDropItem(const struct FRepItemInfo& ItemInfo, class FName ContainerName_0, class AActor** ActorRef);
	void JigMP_OnPickupEquipped(class AActor* ActorRef, class FName ToContainerName, const struct FGuid& UID, const struct FGuid& ToContainerUID, const struct FRepItemInfo& Info, bool* Result, class AActor** OverrideActor);
	void JigMP_OnPickupAdded(const struct FRepItemInfo& Info, const struct FGuid& ItemUID, const struct FGuid& ToContainerUID, class FName ToContainer, bool* Result);
	void JigMP_OnMainContainerItemRemoved(const struct FGuid& FromContainerUID, const struct FGuid& ItemUID, class FName ContainerName_0, const struct FRepItemInfo& ItemRemovedInfo, bool* Result);
	void JigMP_OnMainContainerItemAdded(const struct FGuid& ToContainerUID, const struct FGuid& ItemUID, class FName ToContainerName, const struct FRepItemInfo& ItemInfo, class FName FromMain, bool* Result, class AActor** ActorRef);
	void JigMP_OnItemRemoved(const struct FGuid& ItemUID, const struct FGuid& FromContainerUID, const struct FGuid& ToContainerUID, class UActorComponent* ToComponent, bool* Result);
	void JigMP_OnItemMoved(const struct FGuid& ItemUID, const struct FGuid& FromContainerUID, const struct FGuid& ToContainerUID, bool* Result);
	void JigMP_OnItemDropped(const struct FGuid& ItemUID, const struct FGuid& FromContainerUID, class AActor* ActorRef, bool* Result);
	void JigMP_OnItemConsumed(const struct FRepItemInfo& ConsumedItem, int32 Amount, int32 Remaining, const struct FRepItemInfo& InsideOf, class FName FromContainer, const class FString& CustomData, bool CallbackToPlayer_, bool* Result);
	void JigMP_OnItemAdded(const struct FGuid& ItemUID, const struct FGuid& FromContainerUID, const struct FGuid& ToContainerUID, class UActorComponent* FromComponent, bool* Result);
	void JigMP_OnContainersSwap(class UJSIContainer_C* Container1, class UJSIContainer_C* Container2, bool* Result);
	void JigMP_GetLootWidget(class UWidget** Result, bool* Valid_);
	void JigCanInteract(bool* Result);
	void IsHeld_(bool* Held_);
	void HoldToInteract();
	void GetSettings(double* ChanceToProduceNoise, double* Default_ChanceToProduceNoise, double* DurationToHold_0);
	void GetMainSceneComp(class USceneComponent** Comp);
	void GetJigMultiplayerComponent(class UActorComponent** JigComp);
	void GetItemInfo(class UJigsawItem_DataAsset_C** Info, int32* Count, struct FS_RandomStatsConfig* RandomStatsConfig, TMap<class FString, class FString>* CustomData);
	void GetInteractOptions(TMap<struct FGameplayTag, class FText>* Options);
	void FindItem(class AActor* Actor, bool* Found_);
	void ExecuteUbergraph_BP_MASTER_ToolRequiredContainer(int32 EntryPoint);
	void Event_Outline();
	void Event_MagnifierUI(bool Spawn);
	void Event_HoldToInteract();
	void DistanceOutline();
	void ComponentsToSave(TArray<class UActorComponent*>* Components);
	void CheckDistanceFromActor();
	void BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature(bool bIsBeyondLastLayer, int32 LayerIndex, bool bIsSeen);
	void Bind_Refill();
	void ActorSaved();
	void ActorPreSave();
	void ActorPreLoad();
	void ActorLoaded();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MASTER_ToolRequiredContainer_C">();
	}
	static class ABP_MASTER_ToolRequiredContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MASTER_ToolRequiredContainer_C>();
	}
};
static_assert(alignof(ABP_MASTER_ToolRequiredContainer_C) == 0x000010, "Wrong alignment on ABP_MASTER_ToolRequiredContainer_C");
static_assert(sizeof(ABP_MASTER_ToolRequiredContainer_C) == 0x000410, "Wrong size on ABP_MASTER_ToolRequiredContainer_C");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, UberGraphFrame) == 0x0002A0, "Member 'ABP_MASTER_ToolRequiredContainer_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, AIOSubject) == 0x0002A8, "Member 'ABP_MASTER_ToolRequiredContainer_C::AIOSubject' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, BP_JigMultiplayer) == 0x0002B0, "Member 'ABP_MASTER_ToolRequiredContainer_C::BP_JigMultiplayer' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, StaticMesh) == 0x0002B8, "Member 'ABP_MASTER_ToolRequiredContainer_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, InteractingActorLoc) == 0x0002C0, "Member 'ABP_MASTER_ToolRequiredContainer_C::InteractingActorLoc' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, CurrentActor) == 0x0002D8, "Member 'ABP_MASTER_ToolRequiredContainer_C::CurrentActor' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, Outline_) == 0x0002E0, "Member 'ABP_MASTER_ToolRequiredContainer_C::Outline_' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, IsHeld) == 0x0002E1, "Member 'ABP_MASTER_ToolRequiredContainer_C::IsHeld' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, LootTable) == 0x0002E2, "Member 'ABP_MASTER_ToolRequiredContainer_C::LootTable' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, DurationToHold) == 0x0002E8, "Member 'ABP_MASTER_ToolRequiredContainer_C::DurationToHold' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, ChanceToMakeNoise) == 0x0002F0, "Member 'ABP_MASTER_ToolRequiredContainer_C::ChanceToMakeNoise' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, DefaultChanceToProduceNoise) == 0x0002F8, "Member 'ABP_MASTER_ToolRequiredContainer_C::DefaultChanceToProduceNoise' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, ContainerName) == 0x000300, "Member 'ABP_MASTER_ToolRequiredContainer_C::ContainerName' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, ToolNeeded) == 0x000318, "Member 'ABP_MASTER_ToolRequiredContainer_C::ToolNeeded' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, Opened) == 0x000320, "Member 'ABP_MASTER_ToolRequiredContainer_C::Opened' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, OpenedObject) == 0x000328, "Member 'ABP_MASTER_ToolRequiredContainer_C::OpenedObject' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, ContainerLooted) == 0x000338, "Member 'ABP_MASTER_ToolRequiredContainer_C::ContainerLooted' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, ToolNeeded_) == 0x000339, "Member 'ABP_MASTER_ToolRequiredContainer_C::ToolNeeded_' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, OutlineTimer) == 0x000340, "Member 'ABP_MASTER_ToolRequiredContainer_C::OutlineTimer' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, PlayerClose_) == 0x000348, "Member 'ABP_MASTER_ToolRequiredContainer_C::PlayerClose_' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, HoldToInteractTimer) == 0x000350, "Member 'ABP_MASTER_ToolRequiredContainer_C::HoldToInteractTimer' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, SearchSoundComp) == 0x000358, "Member 'ABP_MASTER_ToolRequiredContainer_C::SearchSoundComp' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, RefillTimer) == 0x000360, "Member 'ABP_MASTER_ToolRequiredContainer_C::RefillTimer' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, MagnifierTransform) == 0x000370, "Member 'ABP_MASTER_ToolRequiredContainer_C::MagnifierTransform' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, W_MagnifierUI) == 0x0003D0, "Member 'ABP_MASTER_ToolRequiredContainer_C::W_MagnifierUI' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, MainJigContainers) == 0x0003D8, "Member 'ABP_MASTER_ToolRequiredContainer_C::MainJigContainers' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, MainUIDs) == 0x0003E8, "Member 'ABP_MASTER_ToolRequiredContainer_C::MainUIDs' has a wrong offset!");
static_assert(offsetof(ABP_MASTER_ToolRequiredContainer_C, Weights) == 0x0003F8, "Member 'ABP_MASTER_ToolRequiredContainer_C::Weights' has a wrong offset!");

}

