#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MilitaryIntelLaptopPickup

#include "Basic.hpp"

#include "BP_StaticMeshPickup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MilitaryIntelLaptopPickup.BP_MilitaryIntelLaptopPickup_C
// 0x0000 (0x0310 - 0x0310)
class ABP_MilitaryIntelLaptopPickup_C final : public ABP_StaticMeshPickup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MilitaryIntelLaptopPickup_C">();
	}
	static class ABP_MilitaryIntelLaptopPickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MilitaryIntelLaptopPickup_C>();
	}
};
static_assert(alignof(ABP_MilitaryIntelLaptopPickup_C) == 0x000008, "Wrong alignment on ABP_MilitaryIntelLaptopPickup_C");
static_assert(sizeof(ABP_MilitaryIntelLaptopPickup_C) == 0x000310, "Wrong size on ABP_MilitaryIntelLaptopPickup_C");

}

