#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Military_Rifleman

#include "Basic.hpp"

#include "BP_MasterMilitary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Military_Rifleman.BP_Military_Rifleman_C
// 0x0000 (0x0A50 - 0x0A50)
class ABP_Military_Rifleman_C final : public ABP_MasterMilitary_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Military_Rifleman_C">();
	}
	static class ABP_Military_Rifleman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Military_Rifleman_C>();
	}
};
static_assert(alignof(ABP_Military_Rifleman_C) == 0x000010, "Wrong alignment on ABP_Military_Rifleman_C");
static_assert(sizeof(ABP_Military_Rifleman_C) == 0x000A50, "Wrong size on ABP_Military_Rifleman_C");

}

