#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuestBranch

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function BP_QuestBranch.BP_QuestBranch_C.ExecuteUbergraph_BP_QuestBranch
// 0x0078 (0x0078 - 0x0000)
struct BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_QuestTask_C*                        CallFunc_Create_ReturnValue;                       // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNarrativeTask*                         CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_QuestTask_C*                        CallFunc_Create_ReturnValue_1;                     // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue_1;      // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNarrativeTask*                         CallFunc_Array_Get_Item_1;                         // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch) == 0x000008, "Wrong alignment on BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch");
static_assert(sizeof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch) == 0x000078, "Wrong size on BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, EntryPoint) == 0x000000, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_bool_Variable) == 0x000004, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_IsValid_ReturnValue) == 0x000005, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_TextIsEmpty_ReturnValue) == 0x000006, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_byte_Variable) == 0x000007, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_byte_Variable_1) == 0x000008, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, K2Node_Select_Default) == 0x000010, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_int_Array_Index_Variable_1) == 0x00001C, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_GetOwningPlayer_ReturnValue) == 0x000020, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Create_ReturnValue) == 0x000028, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Array_Get_Item) == 0x000030, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000040, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000048, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Create_ReturnValue_1) == 0x000050, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_AddChildToVerticalBox_ReturnValue_1) == 0x000058, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_AddChildToVerticalBox_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, Temp_int_Loop_Counter_Variable_1) == 0x000060, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Add_IntInt_ReturnValue_1) == 0x000064, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Array_Get_Item_1) == 0x000068, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Array_Length_ReturnValue_1) == 0x000070, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch, CallFunc_Less_IntInt_ReturnValue_1) == 0x000074, "Member 'BP_QuestBranch_C_ExecuteUbergraph_BP_QuestBranch::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

}

