#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RespawnHUD

#include "Basic.hpp"

#include "BP_RespawnHUD_classes.hpp"
#include "BP_RespawnHUD_parameters.hpp"


namespace SDK
{

// Function BP_RespawnHUD.BP_RespawnHUD_C.BndEvt__RespawnButton_K2Node_ComponentBoundEvent_130_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_RespawnHUD_C::BndEvt__RespawnButton_K2Node_ComponentBoundEvent_130_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RespawnHUD_C", "BndEvt__RespawnButton_K2Node_ComponentBoundEvent_130_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RespawnHUD.BP_RespawnHUD_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_RespawnHUD_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RespawnHUD_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RespawnHUD.BP_RespawnHUD_C.ExecuteUbergraph_BP_RespawnHUD
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_RespawnHUD_C::ExecuteUbergraph_BP_RespawnHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RespawnHUD_C", "ExecuteUbergraph_BP_RespawnHUD");

	Params::BP_RespawnHUD_C_ExecuteUbergraph_BP_RespawnHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

