#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ValkyrieMuzzleBrakePickup

#include "Basic.hpp"

#include "BP_StaticMeshPickup_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ValkyrieMuzzleBrakePickup.BP_ValkyrieMuzzleBrakePickup_C
// 0x0000 (0x0310 - 0x0310)
class ABP_ValkyrieMuzzleBrakePickup_C final : public ABP_StaticMeshPickup_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ValkyrieMuzzleBrakePickup_C">();
	}
	static class ABP_ValkyrieMuzzleBrakePickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ValkyrieMuzzleBrakePickup_C>();
	}
};
static_assert(alignof(ABP_ValkyrieMuzzleBrakePickup_C) == 0x000008, "Wrong alignment on ABP_ValkyrieMuzzleBrakePickup_C");
static_assert(sizeof(ABP_ValkyrieMuzzleBrakePickup_C) == 0x000310, "Wrong size on ABP_ValkyrieMuzzleBrakePickup_C");

}

