#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Zombie_Roamer

#include "Basic.hpp"

#include "BP_Zombie_Roamer_classes.hpp"
#include "BP_Zombie_Roamer_parameters.hpp"


namespace SDK
{

// Function BP_Zombie_Roamer.BP_Zombie_Roamer_C.ExecuteUbergraph_BP_Zombie_Roamer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Zombie_Roamer_C::ExecuteUbergraph_BP_Zombie_Roamer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Zombie_Roamer_C", "ExecuteUbergraph_BP_Zombie_Roamer");

	Params::BP_Zombie_Roamer_C_ExecuteUbergraph_BP_Zombie_Roamer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Zombie_Roamer.BP_Zombie_Roamer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Zombie_Roamer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Zombie_Roamer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

