#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZombieBossRock

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_ZombieBossRock.BP_ZombieBossRock_C.ExecuteUbergraph_BP_ZombieBossRock
// 0x0058 (0x0058 - 0x0000)
struct BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_CustomEvent_Origin;                         // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Target;                         // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BlueprintSuggestProjectileVelocity_TossVelocity; // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BlueprintSuggestProjectileVelocity_ReturnValue; // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock) == 0x000008, "Wrong alignment on BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock");
static_assert(sizeof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock) == 0x000058, "Wrong size on BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock");
static_assert(offsetof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock, EntryPoint) == 0x000000, "Member 'BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock, K2Node_CustomEvent_Origin) == 0x000008, "Member 'BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock::K2Node_CustomEvent_Origin' has a wrong offset!");
static_assert(offsetof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock, K2Node_CustomEvent_Target) == 0x000020, "Member 'BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock::K2Node_CustomEvent_Target' has a wrong offset!");
static_assert(offsetof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock, CallFunc_BlueprintSuggestProjectileVelocity_TossVelocity) == 0x000038, "Member 'BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock::CallFunc_BlueprintSuggestProjectileVelocity_TossVelocity' has a wrong offset!");
static_assert(offsetof(BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock, CallFunc_BlueprintSuggestProjectileVelocity_ReturnValue) == 0x000050, "Member 'BP_ZombieBossRock_C_ExecuteUbergraph_BP_ZombieBossRock::CallFunc_BlueprintSuggestProjectileVelocity_ReturnValue' has a wrong offset!");

// Function BP_ZombieBossRock.BP_ZombieBossRock_C.Launch
// 0x0030 (0x0030 - 0x0000)
struct BP_ZombieBossRock_C_Launch final
{
public:
	struct FVector                                Origin;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Target;                                            // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ZombieBossRock_C_Launch) == 0x000008, "Wrong alignment on BP_ZombieBossRock_C_Launch");
static_assert(sizeof(BP_ZombieBossRock_C_Launch) == 0x000030, "Wrong size on BP_ZombieBossRock_C_Launch");
static_assert(offsetof(BP_ZombieBossRock_C_Launch, Origin) == 0x000000, "Member 'BP_ZombieBossRock_C_Launch::Origin' has a wrong offset!");
static_assert(offsetof(BP_ZombieBossRock_C_Launch, Target) == 0x000018, "Member 'BP_ZombieBossRock_C_Launch::Target' has a wrong offset!");

}

