#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Vehicle

#include "Basic.hpp"

#include "BPI_Vehicle_classes.hpp"
#include "BPI_Vehicle_parameters.hpp"


namespace SDK
{

// Function BPI_Vehicle.BPI_Vehicle_C.OnBeginFuelInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnBeginFuelInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnBeginFuelInteract");

	Params::BPI_Vehicle_C_OnBeginFuelInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPI_Vehicle.BPI_Vehicle_C.OnBeginRepairInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnBeginRepairInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnBeginRepairInteract");

	Params::BPI_Vehicle_C_OnBeginRepairInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPI_Vehicle.BPI_Vehicle_C.OnBeginStorageInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnBeginStorageInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnBeginStorageInteract");

	Params::BPI_Vehicle_C_OnBeginStorageInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPI_Vehicle.BPI_Vehicle_C.OnEndFuelInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnEndFuelInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnEndFuelInteract");

	Params::BPI_Vehicle_C_OnEndFuelInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPI_Vehicle.BPI_Vehicle_C.OnEndRepairInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnEndRepairInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnEndRepairInteract");

	Params::BPI_Vehicle_C_OnEndRepairInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPI_Vehicle.BPI_Vehicle_C.OnEndStorageInteract
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void IBPI_Vehicle_C::OnEndStorageInteract(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Vehicle_C", "OnEndStorageInteract");

	Params::BPI_Vehicle_C_OnEndStorageInteract Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}

}

