#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_WaypointTask

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_WaypointTask.BPI_WaypointTask_C
// 0x0000 (0x0028 - 0x0028)
class IBPI_WaypointTask_C final : public IInterface
{
public:
	void GetTaskLocation(struct FVector* Location);
	void GetTaskLocationName(class FText* Name_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_WaypointTask_C">();
	}
	static class IBPI_WaypointTask_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_WaypointTask_C>();
	}
};
static_assert(alignof(IBPI_WaypointTask_C) == 0x000008, "Wrong alignment on IBPI_WaypointTask_C");
static_assert(sizeof(IBPI_WaypointTask_C) == 0x000028, "Wrong size on IBPI_WaypointTask_C");

}

