#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPT_GoToLocation

#include "Basic.hpp"

#include "Narrative_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPT_GoToLocation.BPT_GoToLocation_C
// 0x0068 (0x00F0 - 0x0088)
class UBPT_GoToLocation_C final : public UNarrativeTask
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                GoalLocation;                                      // 0x0090(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DistanceTolerance;                                 // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   FriendlyLocationName;                              // 0x00B0(0x0018)(Edit, BlueprintVisible)
	TSubclassOf<class AActor>                     GoalActorClass;                                    // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, AdvancedDisplay, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   GoalActorTag;                                      // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	bool                                          Invert_;                                           // 0x00D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 GoalActor;                                         // 0x00E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBP_Narrative3Overlay_C*                NarrativeUI;                                       // 0x00E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void Configure_Goal_Actor();
	void ExecuteUbergraph_BPT_GoToLocation(int32 EntryPoint);
	void GetGoalLocation(struct FVector* GoalLocation_0);
	void GetTaskLocation(struct FVector* Location);
	void GetTaskLocationName(class FText* Name_0);
	void K2_BeginTask();
	void TickTask();

	class FText GetTaskDescription() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPT_GoToLocation_C">();
	}
	static class UBPT_GoToLocation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPT_GoToLocation_C>();
	}
};
static_assert(alignof(UBPT_GoToLocation_C) == 0x000008, "Wrong alignment on UBPT_GoToLocation_C");
static_assert(sizeof(UBPT_GoToLocation_C) == 0x0000F0, "Wrong size on UBPT_GoToLocation_C");
static_assert(offsetof(UBPT_GoToLocation_C, UberGraphFrame) == 0x000088, "Member 'UBPT_GoToLocation_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, GoalLocation) == 0x000090, "Member 'UBPT_GoToLocation_C::GoalLocation' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, DistanceTolerance) == 0x0000A8, "Member 'UBPT_GoToLocation_C::DistanceTolerance' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, FriendlyLocationName) == 0x0000B0, "Member 'UBPT_GoToLocation_C::FriendlyLocationName' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, GoalActorClass) == 0x0000C8, "Member 'UBPT_GoToLocation_C::GoalActorClass' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, GoalActorTag) == 0x0000D0, "Member 'UBPT_GoToLocation_C::GoalActorTag' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, Invert_) == 0x0000D8, "Member 'UBPT_GoToLocation_C::Invert_' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, GoalActor) == 0x0000E0, "Member 'UBPT_GoToLocation_C::GoalActor' has a wrong offset!");
static_assert(offsetof(UBPT_GoToLocation_C, NarrativeUI) == 0x0000E8, "Member 'UBPT_GoToLocation_C::NarrativeUI' has a wrong offset!");

}

