#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_WoodenWallDoor

#include "Basic.hpp"

#include "Buildable_WoodenWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buildable_WoodenWallDoor.Buildable_WoodenWallDoor_C
// 0x0028 (0x0548 - 0x0520)
class ABuildable_WoodenWallDoor_C : public ABuildable_WoodenWall_C
{
public:
	class UBoxComponent*                          NavObstacleBox2;                                   // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          NavObstacleBox1;                                   // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Door2;                                             // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Door1;                                             // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Doors;                                             // 0x0540(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buildable_WoodenWallDoor_C">();
	}
	static class ABuildable_WoodenWallDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildable_WoodenWallDoor_C>();
	}
};
static_assert(alignof(ABuildable_WoodenWallDoor_C) == 0x000008, "Wrong alignment on ABuildable_WoodenWallDoor_C");
static_assert(sizeof(ABuildable_WoodenWallDoor_C) == 0x000548, "Wrong size on ABuildable_WoodenWallDoor_C");
static_assert(offsetof(ABuildable_WoodenWallDoor_C, NavObstacleBox2) == 0x000520, "Member 'ABuildable_WoodenWallDoor_C::NavObstacleBox2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWallDoor_C, NavObstacleBox1) == 0x000528, "Member 'ABuildable_WoodenWallDoor_C::NavObstacleBox1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWallDoor_C, Door2) == 0x000530, "Member 'ABuildable_WoodenWallDoor_C::Door2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWallDoor_C, Door1) == 0x000538, "Member 'ABuildable_WoodenWallDoor_C::Door1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWallDoor_C, Doors) == 0x000540, "Member 'ABuildable_WoodenWallDoor_C::Doors' has a wrong offset!");

}

