#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_WoodenFoundationQuarter

#include "Basic.hpp"

#include "Buildable_WoodenFoundationQuarter_classes.hpp"
#include "Buildable_WoodenFoundationQuarter_parameters.hpp"


namespace SDK
{

// Function Buildable_WoodenFoundationQuarter.Buildable_WoodenFoundationQuarter_C.ExecuteUbergraph_Buildable_WoodenFoundationQuarter
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuildable_WoodenFoundationQuarter_C::ExecuteUbergraph_Buildable_WoodenFoundationQuarter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buildable_WoodenFoundationQuarter_C", "ExecuteUbergraph_Buildable_WoodenFoundationQuarter");

	Params::Buildable_WoodenFoundationQuarter_C_ExecuteUbergraph_Buildable_WoodenFoundationQuarter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buildable_WoodenFoundationQuarter.Buildable_WoodenFoundationQuarter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABuildable_WoodenFoundationQuarter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buildable_WoodenFoundationQuarter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

