#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_BarricadedMetalDoor

#include "Basic.hpp"

#include "S_JigPayload_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Buildable_BarricadedMetalDoor.Buildable_BarricadedMetalDoor_C.BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature final
{
public:
	bool                                          bIsBeyondLastLayer;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LayerIndex;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSeen;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x000004, "Wrong alignment on Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(sizeof(Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x00000C, "Wrong size on Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsBeyondLastLayer) == 0x000000, "Member 'Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, LayerIndex) == 0x000004, "Member 'Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::LayerIndex' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsSeen) == 0x000008, "Member 'Buildable_BarricadedMetalDoor_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsSeen' has a wrong offset!");

// Function Buildable_BarricadedMetalDoor.Buildable_BarricadedMetalDoor_C.ExecuteUbergraph_Buildable_BarricadedMetalDoor
// 0x0218 (0x0218 - 0x0000)
struct Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_Actor;                                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Event_Option;                               // 0x0010(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_ByActor;                              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FS_JigPayload                          K2Node_Event_Payload;                              // 0x0020(0x0030)(HasGetValueTypeHash)
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0070(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue;                         // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x00D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x00F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x0108(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_Dot_VectorVector_ReturnValue;             // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsBeyondLastLayer;     // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F9[0x3];                                      // 0x01F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_ComponentBoundEvent_LayerIndex;             // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSeen;                // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Lerp_Alpha_ImplicitCast;                  // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor) == 0x000008, "Wrong alignment on Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor");
static_assert(sizeof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor) == 0x000218, "Wrong size on Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, EntryPoint) == 0x000000, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::EntryPoint' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_SwitchEnum_CmpSuccess) == 0x000004, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_Event_Actor) == 0x000008, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_Event_Actor' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_Event_Option) == 0x000010, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_Event_Option' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_Event_ByActor) == 0x000018, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_Event_ByActor' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_Event_Payload) == 0x000020, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_Event_Payload' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000050, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000058, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_GetForwardVector_ReturnValue) == 0x000070, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000088, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_GetPlayerCharacter_ReturnValue) == 0x000090, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_GetPlayerCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_SelectFloat_ReturnValue) == 0x000098, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000A0, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_Lerp_ReturnValue) == 0x0000B8, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0000C0, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_MakeRotator_ReturnValue) == 0x0000D8, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_Normal_ReturnValue) == 0x0000F0, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x000108, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_Dot_VectorVector_ReturnValue) == 0x0001F0, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_ComponentBoundEvent_bIsBeyondLastLayer) == 0x0001F8, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_ComponentBoundEvent_bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_ComponentBoundEvent_LayerIndex) == 0x0001FC, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_ComponentBoundEvent_LayerIndex' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, K2Node_ComponentBoundEvent_bIsSeen) == 0x000200, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::K2Node_ComponentBoundEvent_bIsSeen' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_Lerp_Alpha_ImplicitCast) == 0x000208, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_Lerp_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000210, "Member 'Buildable_BarricadedMetalDoor_C_ExecuteUbergraph_Buildable_BarricadedMetalDoor::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");

// Function Buildable_BarricadedMetalDoor.Buildable_BarricadedMetalDoor_C.OnInteractBuildable
// 0x0008 (0x0008 - 0x0000)
struct Buildable_BarricadedMetalDoor_C_OnInteractBuildable final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BarricadedMetalDoor_C_OnInteractBuildable) == 0x000008, "Wrong alignment on Buildable_BarricadedMetalDoor_C_OnInteractBuildable");
static_assert(sizeof(Buildable_BarricadedMetalDoor_C_OnInteractBuildable) == 0x000008, "Wrong size on Buildable_BarricadedMetalDoor_C_OnInteractBuildable");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_OnInteractBuildable, Actor) == 0x000000, "Member 'Buildable_BarricadedMetalDoor_C_OnInteractBuildable::Actor' has a wrong offset!");

// Function Buildable_BarricadedMetalDoor.Buildable_BarricadedMetalDoor_C.OnServerExecuteInteract
// 0x0040 (0x0040 - 0x0000)
struct Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract final
{
public:
	struct FGameplayTag                           Option;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ByActor;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FS_JigPayload                          Payload;                                           // 0x0010(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract) == 0x000008, "Wrong alignment on Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract");
static_assert(sizeof(Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract) == 0x000040, "Wrong size on Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract, Option) == 0x000000, "Member 'Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract::Option' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract, ByActor) == 0x000008, "Member 'Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract::ByActor' has a wrong offset!");
static_assert(offsetof(Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract, Payload) == 0x000010, "Member 'Buildable_BarricadedMetalDoor_C_OnServerExecuteInteract::Payload' has a wrong offset!");

}

