#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_TrashBin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buildable_MASTER_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buildable_TrashBin.Buildable_TrashBin_C
// 0x0018 (0x0448 - 0x0430)
class ABuildable_TrashBin_C final : public ABuildable_MASTER_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Buildable_TrashBin_C;               // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<int32>                                 BatteryUIDs;                                       // 0x0438(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature(bool bIsBeyondLastLayer, int32 LayerIndex, bool bIsSeen);
	void ExecuteUbergraph_Buildable_TrashBin(int32 EntryPoint);
	void JigMP_OnRequestDropItem(const struct FRepItemInfo& ItemInfo, class FName ContainerName, class AActor** ActorRef);
	void OnInteractBuildable(class AActor* Actor);
	void OnServerExecuteInteract(const struct FGameplayTag& Option, class AActor* ByActor, const struct FS_JigPayload& Payload);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buildable_TrashBin_C">();
	}
	static class ABuildable_TrashBin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildable_TrashBin_C>();
	}
};
static_assert(alignof(ABuildable_TrashBin_C) == 0x000008, "Wrong alignment on ABuildable_TrashBin_C");
static_assert(sizeof(ABuildable_TrashBin_C) == 0x000448, "Wrong size on ABuildable_TrashBin_C");
static_assert(offsetof(ABuildable_TrashBin_C, UberGraphFrame_Buildable_TrashBin_C) == 0x000430, "Member 'ABuildable_TrashBin_C::UberGraphFrame_Buildable_TrashBin_C' has a wrong offset!");
static_assert(offsetof(ABuildable_TrashBin_C, BatteryUIDs) == 0x000438, "Member 'ABuildable_TrashBin_C::BatteryUIDs' has a wrong offset!");

}

