#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_WoodenWall

#include "Basic.hpp"

#include "Buildable_ModularMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buildable_WoodenWall.Buildable_WoodenWall_C
// 0x00E8 (0x0520 - 0x0438)
class ABuildable_WoodenWall_C : public ABuildable_ModularMaster_C
{
public:
	class UChildActorComponent*                   RoofTop2;                                          // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   RoofTop1;                                          // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        RoofTops;                                          // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf6;                                         // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf5;                                         // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf4;                                         // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf3;                                         // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf2;                                         // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf1;                                         // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        WallsHalves;                                       // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        FloorTriangles;                                    // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorTriangle1;                                    // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorTriangle2;                                    // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorQuarter1;                                     // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorQuarter4;                                     // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorQuarter3;                                     // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FloorQuarter2;                                     // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        FloorQuarters;                                     // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall3;                                             // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall4;                                             // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall1;                                             // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall2;                                             // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Walls;                                             // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Roof1;                                             // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Roof2;                                             // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Roof;                                              // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Floors;                                            // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Floor1;                                            // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Floor2;                                            // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buildable_WoodenWall_C">();
	}
	static class ABuildable_WoodenWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildable_WoodenWall_C>();
	}
};
static_assert(alignof(ABuildable_WoodenWall_C) == 0x000008, "Wrong alignment on ABuildable_WoodenWall_C");
static_assert(sizeof(ABuildable_WoodenWall_C) == 0x000520, "Wrong size on ABuildable_WoodenWall_C");
static_assert(offsetof(ABuildable_WoodenWall_C, RoofTop2) == 0x000438, "Member 'ABuildable_WoodenWall_C::RoofTop2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, RoofTop1) == 0x000440, "Member 'ABuildable_WoodenWall_C::RoofTop1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, RoofTops) == 0x000448, "Member 'ABuildable_WoodenWall_C::RoofTops' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf6) == 0x000450, "Member 'ABuildable_WoodenWall_C::WallHalf6' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf5) == 0x000458, "Member 'ABuildable_WoodenWall_C::WallHalf5' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf4) == 0x000460, "Member 'ABuildable_WoodenWall_C::WallHalf4' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf3) == 0x000468, "Member 'ABuildable_WoodenWall_C::WallHalf3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf2) == 0x000470, "Member 'ABuildable_WoodenWall_C::WallHalf2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallHalf1) == 0x000478, "Member 'ABuildable_WoodenWall_C::WallHalf1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, WallsHalves) == 0x000480, "Member 'ABuildable_WoodenWall_C::WallsHalves' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorTriangles) == 0x000488, "Member 'ABuildable_WoodenWall_C::FloorTriangles' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorTriangle1) == 0x000490, "Member 'ABuildable_WoodenWall_C::FloorTriangle1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorTriangle2) == 0x000498, "Member 'ABuildable_WoodenWall_C::FloorTriangle2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorQuarter1) == 0x0004A0, "Member 'ABuildable_WoodenWall_C::FloorQuarter1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorQuarter4) == 0x0004A8, "Member 'ABuildable_WoodenWall_C::FloorQuarter4' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorQuarter3) == 0x0004B0, "Member 'ABuildable_WoodenWall_C::FloorQuarter3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorQuarter2) == 0x0004B8, "Member 'ABuildable_WoodenWall_C::FloorQuarter2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, FloorQuarters) == 0x0004C0, "Member 'ABuildable_WoodenWall_C::FloorQuarters' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Wall3) == 0x0004C8, "Member 'ABuildable_WoodenWall_C::Wall3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Wall4) == 0x0004D0, "Member 'ABuildable_WoodenWall_C::Wall4' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Wall1) == 0x0004D8, "Member 'ABuildable_WoodenWall_C::Wall1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Wall2) == 0x0004E0, "Member 'ABuildable_WoodenWall_C::Wall2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Walls) == 0x0004E8, "Member 'ABuildable_WoodenWall_C::Walls' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Roof1) == 0x0004F0, "Member 'ABuildable_WoodenWall_C::Roof1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Roof2) == 0x0004F8, "Member 'ABuildable_WoodenWall_C::Roof2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Roof) == 0x000500, "Member 'ABuildable_WoodenWall_C::Roof' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Floors) == 0x000508, "Member 'ABuildable_WoodenWall_C::Floors' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Floor1) == 0x000510, "Member 'ABuildable_WoodenWall_C::Floor1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenWall_C, Floor2) == 0x000518, "Member 'ABuildable_WoodenWall_C::Floor2' has a wrong offset!");

}

