#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_WoodenFoundationTriangle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buildable_ModularMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buildable_WoodenFoundationTriangle.Buildable_WoodenFoundationTriangle_C
// 0x00F0 (0x0528 - 0x0438)
class ABuildable_WoodenFoundationTriangle_C final : public ABuildable_ModularMaster_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Buildable_WoodenFoundationTriangle_C; // 0x0438(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UChildActorComponent*                   StairsHalf9;                                       // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf8;                                       // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf7;                                       // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf6;                                       // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf5;                                       // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf4;                                       // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf3;                                       // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf2;                                       // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FoundationTriangle3;                               // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FoundationTriangle2;                               // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        FoundationTriangles;                               // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   FoundationTriangle1;                               // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   StairsHalf1;                                       // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        StairsHalf;                                        // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf2;                                         // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf4;                                         // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf5;                                         // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf3;                                         // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf1;                                         // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   WallHalf6;                                         // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        WallHalves;                                        // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Foundation1;                                       // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Foundation2;                                       // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Foundation3;                                       // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Foundations;                                       // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall2;                                             // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall1;                                             // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   Wall3;                                             // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Walls;                                             // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Buildable_WoodenFoundationTriangle(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buildable_WoodenFoundationTriangle_C">();
	}
	static class ABuildable_WoodenFoundationTriangle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildable_WoodenFoundationTriangle_C>();
	}
};
static_assert(alignof(ABuildable_WoodenFoundationTriangle_C) == 0x000008, "Wrong alignment on ABuildable_WoodenFoundationTriangle_C");
static_assert(sizeof(ABuildable_WoodenFoundationTriangle_C) == 0x000528, "Wrong size on ABuildable_WoodenFoundationTriangle_C");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, UberGraphFrame_Buildable_WoodenFoundationTriangle_C) == 0x000438, "Member 'ABuildable_WoodenFoundationTriangle_C::UberGraphFrame_Buildable_WoodenFoundationTriangle_C' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf9) == 0x000440, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf9' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf8) == 0x000448, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf8' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf7) == 0x000450, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf7' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf6) == 0x000458, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf6' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf5) == 0x000460, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf5' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf4) == 0x000468, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf4' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf3) == 0x000470, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf2) == 0x000478, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, FoundationTriangle3) == 0x000480, "Member 'ABuildable_WoodenFoundationTriangle_C::FoundationTriangle3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, FoundationTriangle2) == 0x000488, "Member 'ABuildable_WoodenFoundationTriangle_C::FoundationTriangle2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, FoundationTriangles) == 0x000490, "Member 'ABuildable_WoodenFoundationTriangle_C::FoundationTriangles' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, FoundationTriangle1) == 0x000498, "Member 'ABuildable_WoodenFoundationTriangle_C::FoundationTriangle1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf1) == 0x0004A0, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, StairsHalf) == 0x0004A8, "Member 'ABuildable_WoodenFoundationTriangle_C::StairsHalf' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf2) == 0x0004B0, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf4) == 0x0004B8, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf4' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf5) == 0x0004C0, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf5' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf3) == 0x0004C8, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf1) == 0x0004D0, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalf6) == 0x0004D8, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalf6' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, WallHalves) == 0x0004E0, "Member 'ABuildable_WoodenFoundationTriangle_C::WallHalves' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Foundation1) == 0x0004E8, "Member 'ABuildable_WoodenFoundationTriangle_C::Foundation1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Foundation2) == 0x0004F0, "Member 'ABuildable_WoodenFoundationTriangle_C::Foundation2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Foundation3) == 0x0004F8, "Member 'ABuildable_WoodenFoundationTriangle_C::Foundation3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Foundations) == 0x000500, "Member 'ABuildable_WoodenFoundationTriangle_C::Foundations' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Wall2) == 0x000508, "Member 'ABuildable_WoodenFoundationTriangle_C::Wall2' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Wall1) == 0x000510, "Member 'ABuildable_WoodenFoundationTriangle_C::Wall1' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Wall3) == 0x000518, "Member 'ABuildable_WoodenFoundationTriangle_C::Wall3' has a wrong offset!");
static_assert(offsetof(ABuildable_WoodenFoundationTriangle_C, Walls) == 0x000520, "Member 'ABuildable_WoodenFoundationTriangle_C::Walls' has a wrong offset!");

}

