#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buildable_BaseMarker

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Buildable_BaseMarker.Buildable_BaseMarker_C.BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature final
{
public:
	bool                                          bIsBeyondLastLayer;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LayerIndex;                                        // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSeen;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x000004, "Wrong alignment on Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(sizeof(Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature) == 0x00000C, "Wrong size on Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature");
static_assert(offsetof(Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsBeyondLastLayer) == 0x000000, "Member 'Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, LayerIndex) == 0x000004, "Member 'Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::LayerIndex' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature, bIsSeen) == 0x000008, "Member 'Buildable_BaseMarker_C_BndEvt__BP_CookingStation_AIOSubject_K2Node_ComponentBoundEvent_0_OnOptimizationUpdate__DelegateSignature::bIsSeen' has a wrong offset!");

// Function Buildable_BaseMarker.Buildable_BaseMarker_C.ExecuteUbergraph_Buildable_BaseMarker
// 0x0170 (0x0170 - 0x0000)
struct Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)(ConstParm)
	class UBPC_MinimapSystem_C*                   CallFunc_Get_Minimap_Component_ReturnValue;        // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_1;                              // 0x0028(0x0018)(ConstParm)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0040(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_StandardMarker_C*                    CallFunc_Array_Get_Item;                           // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x00A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x00C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x00D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00F0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Marker_C*                           CallFunc_FinishSpawningActor_ReturnValue;          // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsBeyondLastLayer;     // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x3];                                      // 0x0161(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_ComponentBoundEvent_LayerIndex;             // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSeen;                // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker) == 0x000010, "Wrong alignment on Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker");
static_assert(sizeof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker) == 0x000170, "Wrong size on Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, EntryPoint) == 0x000000, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::EntryPoint' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, Temp_text_Variable) == 0x000008, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_Get_Minimap_Component_ReturnValue) == 0x000020, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_Get_Minimap_Component_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, Temp_text_Variable_1) == 0x000028, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_GetTransform_ReturnValue) == 0x000040, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_Array_Get_Item) == 0x0000A0, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_BreakTransform_Location) == 0x0000A8, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_BreakTransform_Rotation) == 0x0000C0, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_BreakTransform_Scale) == 0x0000D8, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_MakeTransform_ReturnValue) == 0x0000F0, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000150, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, CallFunc_FinishSpawningActor_ReturnValue) == 0x000158, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, K2Node_ComponentBoundEvent_bIsBeyondLastLayer) == 0x000160, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::K2Node_ComponentBoundEvent_bIsBeyondLastLayer' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, K2Node_ComponentBoundEvent_LayerIndex) == 0x000164, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::K2Node_ComponentBoundEvent_LayerIndex' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, K2Node_ComponentBoundEvent_bIsSeen) == 0x000168, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::K2Node_ComponentBoundEvent_bIsSeen' has a wrong offset!");
static_assert(offsetof(Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker, K2Node_SwitchInteger_CmpSuccess) == 0x000169, "Member 'Buildable_BaseMarker_C_ExecuteUbergraph_Buildable_BaseMarker::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

}

