#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Container_AmmoLoot_AmmoBox

#include "Basic.hpp"


namespace SDK::Params
{

// Function Container_AmmoLoot_AmmoBox.Container_AmmoLoot_AmmoBox_C.ExecuteUbergraph_Container_AmmoLoot_AmmoBox
// 0x0024 (0x0024 - 0x0000)
struct Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox) == 0x000004, "Wrong alignment on Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox");
static_assert(sizeof(Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox) == 0x000024, "Wrong size on Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox");
static_assert(offsetof(Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox, EntryPoint) == 0x000000, "Member 'Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox::EntryPoint' has a wrong offset!");
static_assert(offsetof(Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'Container_AmmoLoot_AmmoBox_C_ExecuteUbergraph_Container_AmmoLoot_AmmoBox::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");

}

