#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Container_IndustrialLoot_Crates

#include "Basic.hpp"

#include "Container_IndustrialLoot_Crates_classes.hpp"
#include "Container_IndustrialLoot_Crates_parameters.hpp"


namespace SDK
{

// Function Container_IndustrialLoot_Crates.Container_IndustrialLoot_Crates_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AContainer_IndustrialLoot_Crates_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Container_IndustrialLoot_Crates_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Container_IndustrialLoot_Crates.Container_IndustrialLoot_Crates_C.ExecuteUbergraph_Container_IndustrialLoot_Crates
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AContainer_IndustrialLoot_Crates_C::ExecuteUbergraph_Container_IndustrialLoot_Crates(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Container_IndustrialLoot_Crates_C", "ExecuteUbergraph_Container_IndustrialLoot_Crates");

	Params::Container_IndustrialLoot_Crates_C_ExecuteUbergraph_Container_IndustrialLoot_Crates Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Container_IndustrialLoot_Crates.Container_IndustrialLoot_Crates_C.Event2
// (BlueprintCallable, BlueprintEvent)

void AContainer_IndustrialLoot_Crates_C::Event2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Container_IndustrialLoot_Crates_C", "Event2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Container_IndustrialLoot_Crates.Container_IndustrialLoot_Crates_C.Event1
// (BlueprintCallable, BlueprintEvent)

void AContainer_IndustrialLoot_Crates_C::Event1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Container_IndustrialLoot_Crates_C", "Event1");

	UObject::ProcessEvent(Func, nullptr);
}

}

