#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Container_GunCaseLoot_DisplayCase2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Container_GunCaseLoot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Container_GunCaseLoot_DisplayCase2.Container_GunCaseLoot_DisplayCase2_C
// 0x0010 (0x0450 - 0x0440)
class AContainer_GunCaseLoot_DisplayCase2_C final : public AContainer_GunCaseLoot_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Container_GunCaseLoot_DisplayCase2_C; // 0x0440(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Container_GunCaseLoot_DisplayCase2(int32 EntryPoint);
	void Event2();
	void Event1();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Container_GunCaseLoot_DisplayCase2_C">();
	}
	static class AContainer_GunCaseLoot_DisplayCase2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AContainer_GunCaseLoot_DisplayCase2_C>();
	}
};
static_assert(alignof(AContainer_GunCaseLoot_DisplayCase2_C) == 0x000010, "Wrong alignment on AContainer_GunCaseLoot_DisplayCase2_C");
static_assert(sizeof(AContainer_GunCaseLoot_DisplayCase2_C) == 0x000450, "Wrong size on AContainer_GunCaseLoot_DisplayCase2_C");
static_assert(offsetof(AContainer_GunCaseLoot_DisplayCase2_C, UberGraphFrame_Container_GunCaseLoot_DisplayCase2_C) == 0x000440, "Member 'AContainer_GunCaseLoot_DisplayCase2_C::UberGraphFrame_Container_GunCaseLoot_DisplayCase2_C' has a wrong offset!");

}

