#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dialogue_MaterialsTrader

#include "Basic.hpp"


namespace SDK::Params
{

// Function Dialogue_MaterialsTrader.Dialogue_MaterialsTrader_C.ExecuteUbergraph_Dialogue_MaterialsTrader
// 0x0004 (0x0004 - 0x0000)
struct Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader) == 0x000004, "Wrong alignment on Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader");
static_assert(sizeof(Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader) == 0x000004, "Wrong size on Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader");
static_assert(offsetof(Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader, EntryPoint) == 0x000000, "Member 'Dialogue_MaterialsTrader_C_ExecuteUbergraph_Dialogue_MaterialsTrader::EntryPoint' has a wrong offset!");

}

