#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DropItemBackGwidget

#include "Basic.hpp"

#include "DropItemBackGwidget_classes.hpp"
#include "DropItemBackGwidget_parameters.hpp"


namespace SDK
{

// Function DropItemBackGwidget.DropItemBackGwidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDropItemBackGwidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DropItemBackGwidget.DropItemBackGwidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDropItemBackGwidget_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DropItemBackGwidget.DropItemBackGwidget_C.ExecuteUbergraph_DropItemBackGwidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDropItemBackGwidget_C::ExecuteUbergraph_DropItemBackGwidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "ExecuteUbergraph_DropItemBackGwidget");

	Params::DropItemBackGwidget_C_ExecuteUbergraph_DropItemBackGwidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DropItemBackGwidget.DropItemBackGwidget_C.OnDrop
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    PointerEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class UDragDropOperation*               Operation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UDropItemBackGwidget_C::OnDrop(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "OnDrop");

	Params::DropItemBackGwidget_C_OnDrop Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.PointerEvent = std::move(PointerEvent);
	Parms.Operation = Operation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DropItemBackGwidget.DropItemBackGwidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDropItemBackGwidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "PreConstruct");

	Params::DropItemBackGwidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DropItemBackGwidget.DropItemBackGwidget_C.Show Vendor Amount Selected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UJSI_Slot_C*                      ItemRef                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UJSIContainer_C*                  ToContainerRef                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UDropItemBackGwidget_C::Show_Vendor_Amount_Selected(class UJSI_Slot_C* ItemRef, class UJSIContainer_C* ToContainerRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DropItemBackGwidget_C", "Show Vendor Amount Selected");

	Params::DropItemBackGwidget_C_Show_Vendor_Amount_Selected Parms{};

	Parms.ItemRef = ItemRef;
	Parms.ToContainerRef = ToContainerRef;

	UObject::ProcessEvent(Func, &Parms);
}

}

