#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Journal_QuestsUI

#include "Basic.hpp"

#include "Journal_QuestsUI_classes.hpp"
#include "Journal_QuestsUI_parameters.hpp"


namespace SDK
{

// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_ActiveButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_Button_Quest_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_Button_Quest_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_Button_Quest_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UJournal_QuestsUI_C::BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "BndEvt__Journal_QuestsUI_CompletedButton_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Clear Quest
// (BlueprintCallable, BlueprintEvent)

void UJournal_QuestsUI_C::Clear_Quest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Clear Quest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UJournal_QuestsUI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.ExecuteUbergraph_Journal_QuestsUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UJournal_QuestsUI_C::ExecuteUbergraph_Journal_QuestsUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "ExecuteUbergraph_Journal_QuestsUI");

	Params::Journal_QuestsUI_C_ExecuteUbergraph_Journal_QuestsUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.ForgetQuest
// (BlueprintCallable, BlueprintEvent)

void UJournal_QuestsUI_C::ForgetQuest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "ForgetQuest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Get_SaveEnabledIcon_ToolTipWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UJournal_QuestsUI_C::Get_SaveEnabledIcon_ToolTipWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Get_SaveEnabledIcon_ToolTipWidget");

	Params::Journal_QuestsUI_C_Get_SaveEnabledIcon_ToolTipWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.GetAllActiveQuests
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UJournal_QuestsUI_C::GetAllActiveQuests()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "GetAllActiveQuests");

	Params::Journal_QuestsUI_C_GetAllActiveQuests Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.GetAllCompletedQuests
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UJournal_QuestsUI_C::GetAllCompletedQuests()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "GetAllCompletedQuests");

	Params::Journal_QuestsUI_C_GetAllCompletedQuests Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNarrativeComponent*              Narrative                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UJournal_QuestsUI_C::Initialize(class UNarrativeComponent* Narrative)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Initialize");

	Params::Journal_QuestsUI_C_Initialize Parms{};

	Parms.Narrative = Narrative;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Initialize_Completed
// (BlueprintCallable, BlueprintEvent)

void UJournal_QuestsUI_C::Initialize_Completed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Initialize_Completed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Journal_QuestsUI.Journal_QuestsUI_C.Show Quest
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UQuest*                           Quest                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UJournal_QuestsUI_C::Show_Quest(class UQuest* Quest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Journal_QuestsUI_C", "Show Quest");

	Params::Journal_QuestsUI_C_Show_Quest Parms{};

	Parms.Quest = Quest;

	UObject::ProcessEvent(Func, &Parms);
}

}

