#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Quest_LaptopEvent_ClassifiedContainer007

#include "Basic.hpp"

#include "Narrative_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// QuestBlueprintGeneratedClass Quest_LaptopEvent_ClassifiedContainer007.Quest_LaptopEvent_ClassifiedContainer007_C
// 0x0008 (0x0178 - 0x0170)
class UQuest_LaptopEvent_ClassifiedContainer007_C final : public UQuest
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0170(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Quest_LaptopEvent_ClassifiedContainer007(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Quest_LaptopEvent_ClassifiedContainer007_C">();
	}
	static class UQuest_LaptopEvent_ClassifiedContainer007_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuest_LaptopEvent_ClassifiedContainer007_C>();
	}
};
static_assert(alignof(UQuest_LaptopEvent_ClassifiedContainer007_C) == 0x000008, "Wrong alignment on UQuest_LaptopEvent_ClassifiedContainer007_C");
static_assert(sizeof(UQuest_LaptopEvent_ClassifiedContainer007_C) == 0x000178, "Wrong size on UQuest_LaptopEvent_ClassifiedContainer007_C");
static_assert(offsetof(UQuest_LaptopEvent_ClassifiedContainer007_C, UberGraphFrame) == 0x000170, "Member 'UQuest_LaptopEvent_ClassifiedContainer007_C::UberGraphFrame' has a wrong offset!");

}

