#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SC_HuntingVest

#include "Basic.hpp"

#include "SC_HuntingVest_classes.hpp"
#include "SC_HuntingVest_parameters.hpp"


namespace SDK
{

// Function SC_HuntingVest.SC_HuntingVest_C.ExecuteUbergraph_SC_HuntingVest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USC_HuntingVest_C::ExecuteUbergraph_SC_HuntingVest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SC_HuntingVest_C", "ExecuteUbergraph_SC_HuntingVest");

	Params::SC_HuntingVest_C_ExecuteUbergraph_SC_HuntingVest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SC_HuntingVest.SC_HuntingVest_C.PreInitSpecialContainer
// (BlueprintCallable, BlueprintEvent)

void USC_HuntingVest_C::PreInitSpecialContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SC_HuntingVest_C", "PreInitSpecialContainer");

	UObject::ProcessEvent(Func, nullptr);
}

}

