#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_NarrativeButtonHovered

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle_NarrativeButtonHovered.TextStyle_NarrativeButtonHovered_C
// 0x0000 (0x01B0 - 0x01B0)
class UTextStyle_NarrativeButtonHovered_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle_NarrativeButtonHovered_C">();
	}
	static class UTextStyle_NarrativeButtonHovered_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_NarrativeButtonHovered_C>();
	}
};
static_assert(alignof(UTextStyle_NarrativeButtonHovered_C) == 0x000010, "Wrong alignment on UTextStyle_NarrativeButtonHovered_C");
static_assert(sizeof(UTextStyle_NarrativeButtonHovered_C) == 0x0001B0, "Wrong size on UTextStyle_NarrativeButtonHovered_C");

}

